name: Build and Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'
      - name: Generate firebase_web_options.dart from template
        run: |
          sed -e "s|FIREBASE_API_KEY|${{ secrets.FIREBASE_API_KEY }}|g" \
              -e "s|FIREBASE_APP_ID|${{ secrets.FIREBASE_APP_ID }}|g" \
              -e "s|FIREBASE_MESSAGING_SENDER_ID|${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}|g" \
              -e "s|FIREBASE_PROJECT_ID|${{ secrets.FIREBASE_PROJECT_ID }}|g" \
              -e "s|FIREBASE_AUTH_DOMAIN|${{ secrets.FIREBASE_AUTH_DOMAIN }}|g" \
              -e "s|FIREBASE_DATABASE_URL|${{ secrets.FIREBASE_DATABASE_URL }}|g" \
              -e "s|FIREBASE_STORAGE_BUCKET|${{ secrets.FIREBASE_STORAGE_BUCKET }}|g" \
              -e "s|FIREBASE_MEASUREMENT_ID|${{ secrets.FIREBASE_MEASUREMENT_ID }}|g" \
              -e "s|FIREBASE_DATABASE_URL|${{ secrets.FIREBASE_DATABASE_URL }}|g" \
              lib/firebase_options_template.dart > lib/firebase_options.dart
      - run: flutter pub get
      - run: flutter build web --release --dart-define=RECAPTCHA_SITE_KEY=${{ secrets.RECAPTCHA_SITE_KEY }}
      - uses: w9jds/firebase-action@v12.4.0
        with:
          args: deploy --only hosting --project acornstoacorns
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
